# Generated by Django 4.1.1 on 2022-10-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WS_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ws_ip', models.GenericIPAddressField()),
                ('loc', models.CharField(max_length=200)),
            ],
        ),
    ]
